#TODO get the ENUMS working and come up with a good RegExp pattern for registry.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandodebundles.entando.org
spec:
  group: entando.org
  version: v1alpha1
  names:
    kind: EntandoDeBundle
    plural: entandodebundles
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            details:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                dist-tags:
                  type: object
                versions:
                  type: array
                  items:
                    type: string
                keywords:
                  type: array
                  items:
                    type: string
              additionalProperties: true
            tags:
              type: array
              items:
                type: object
                properties:
                  version:
                    type: string
                  integrity:
                    type: string
                  shasum: 
                    type: string
                  tarball:
                    type: string
        entandoStatus: {}

